services:
  postgres:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
  mysql:
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    image: mysql:8.0
    ports:
      - "3306:3306"
    command:
      [
        '--max_allowed_packet=1GB',
        '--default-authentication-plugin=mysql_native_password'
      ]
    environment:
      MYSQL_DATABASE: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
  admin:
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    network_mode: host
    image: adminer
    restart: always
    depends_on:
      - postgres
      - mysql
    environment:
      ADMINER_DESIGN: dracula
      ADMINER_PLUGINS: 'tables-filter tinymce json-column struct-comments table-structure table-indexes-structure frames'
    volumes:
      - ./data/adminer/0-upload_large_dumps.ini:/etc/php/7.4/cli/conf.d/0-upload_large_dumps.ini
      - ./data/adminer/0-upload_large_dumps.ini:/etc/php/7.4/fpm/conf.d/0-upload_large_dumps.ini
  redis:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes:
      - ./data/redis:/data

volumes:
  mysql:
    driver: local
  postgres:
    driver: local
  redis:
    driver: local
